/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./frontend/**/*.{html,js}"],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#e5e2da",
        "on-background": "#e5e2da",
        "on-error": "#690005",
        "primary-fixed-dim": "#ffb3b6",
        "outline-variant": "#5d3f40",
        "on-surface": "#e5e2da",
        "surface-tint": "#ffb3b6",
        tertiary: "#ffb59e",
        primary: "#ffb3b6",
        "on-tertiary": "#5e1700",
        "tertiary-container": "#ec683d",
        "secondary-fixed-dim": "#68dbae",
        "inverse-on-surface": "#31312b",
        outline: "#ad8889",
        "surface-container-lowest": "#0e0f0a",
        "surface-bright": "#393934",
        "on-surface-variant": "#e6bcbd",
        "surface-variant": "#353530",
        "error-container": "#93000a",
        secondary: "#68dbae",
        "secondary-fixed": "#86f8c9",
        "surface-container": "#20201b",
        error: "#ffb4ab",
        "on-secondary": "#003827",
        "on-primary-container": "#5b0015",
        "on-error-container": "#ffdad6",
        "primary-container": "#ff5168",
        "surface-container-high": "#2a2a25",
        surface: "#13140f",
        background: "#13140f",
        "on-primary": "#680019",
        "surface-container-low": "#1c1c17",
        "primary-fixed": "#ffdada",
        "inverse-primary": "#be0036",
        "surface-dim": "#13140f",
        "secondary-container": "#26a37a",
        "surface-container-highest": "#353530",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "32px",
        gutter: "20px",
        xl: "40px",
        lg: "24px",
        md: "16px",
        unit: "4px",
        xs: "4px",
        "margin-mobile": "16px",
        sm: "8px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter"],
        "body-base": ["Inter"],
        "headline-lg": ["Inter"],
        "display-lg": ["Inter"],
        "title-md": ["Inter"],
        "label-sm": ["Inter"],
        "data-mono": ["JetBrains Mono"],
      },
      fontSize: {
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "1.2", fontWeight: "700" },
        ],
        "body-base": ["15px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": [
          "32px",
          {
            lineHeight: "1.2",
            letterSpacing: "-0.01em",
            fontWeight: "700",
          },
        ],
        "title-md": ["18px", { lineHeight: "1.4", fontWeight: "600" }],
        "label-sm": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "data-mono": ["14px", { lineHeight: "1.4", fontWeight: "500" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
