/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./frontend/**/*.{html,js}"],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#e5e2da",
        "on-background": "#e5e2da",
        "on-error": "#690005",
        "primary-fixed-dim": "#00F2EA",
        "outline-variant": "#353530",
        "on-surface": "#e5e2da",
        "surface-tint": "#00F2EA",
        tertiary: "#FF0050",
        primary: "#00F2EA",
        "on-tertiary": "#00001a",
        "tertiary-container": "#cc0040",
        "secondary-fixed-dim": "#00C853",
        "inverse-on-surface": "#31312b",
        outline: "#4a4a45",
        "surface-container-lowest": "#0e0f0a",
        "surface-bright": "#393934",
        "on-surface-variant": "#a7a7a0",
        "surface-variant": "#353530",
        "error-container": "#93000a",
        secondary: "#00C853",
        "secondary-fixed": "#00e676",
        "surface-container": "#20201b",
        error: "#ffb4ab",
        "on-secondary": "#003d1a",
        "on-primary-container": "#003d3b",
        "on-error-container": "#ffdad6",
        "primary-container": "#00c8be",
        "surface-container-high": "#2a2a25",
        surface: "#161711",
        background: "#0e0f0a",
        "on-primary": "#003d3b",
        "surface-container-low": "#1c1c17",
        "primary-fixed": "#ccfffd",
        "inverse-primary": "#006b67",
        "surface-dim": "#0e0f0a",
        "secondary-container": "#00a344",
        "surface-container-highest": "#353530",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "32px",
        gutter: "20px",
        xl: "40px",
        lg: "24px",
        md: "16px",
        unit: "4px",
        xs: "4px",
        "margin-mobile": "16px",
        sm: "8px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter"],
        "body-base": ["Inter"],
        "headline-lg": ["Inter"],
        "display-lg": ["Inter"],
        "title-md": ["Inter"],
        "label-sm": ["Inter"],
        "data-mono": ["JetBrains Mono"],
      },
      fontSize: {
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "1.2", fontWeight: "700" },
        ],
        "body-base": ["15px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": [
          "32px",
          {
            lineHeight: "1.2",
            letterSpacing: "-0.01em",
            fontWeight: "700",
          },
        ],
        "title-md": ["18px", { lineHeight: "1.4", fontWeight: "600" }],
        "label-sm": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "data-mono": ["14px", { lineHeight: "1.4", fontWeight: "500" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
